# Generated by Django 6.0.7 on 2026-07-18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0002_alter_todo_options_alter_todo_description_and_more'),
    ]

    operations = [
        # A validação foi implementada via Todo.clean(); não requer alteração de schema
    ]


