# Generated by Django 6.0.7 on 2026-07-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_todo_deadline_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
